import Head from "next/head";
import Header from "@/components/header";
import HeroSection from "@/components/hero-section";
import Details1 from "@/components/details1";
import SoundFamiliar from "@/components/soundFamiliar";
import { Box } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box px={{ base: "5px", md: "20px" }}>
        <Header />
        <HeroSection />
        <Details1 />
        <SoundFamiliar />
      </Box>
    </>
  );
}
